### ISSUE TITLE
Front End Web Dev Track

### ISSUE THREAD

**Issue by alljones** [alljones/treehouse#1]
## TODO
Started January 20, 2017
_Courses left to complete this track:_

- [ ] How To Make a Website
- [ ] CSS Basics
- [ ] Javascript Basics
- [ ] CSS Layout Basic
- [ ] Responsive Layout
- [ ] CSS Flexbox Layout
- [ ] HTML Forms
- [ ] Javascript Loops, Arrays and Objects
- [ ] CSS Selectors
- [ ] jQuery Basics
- [ ] Bootstrap 4 Basics
- [ ] HTML Tables
- [ ] HTML Video & Audio
- [ ] AJAX Basics
- [ ] Object Oriented Javascript
- [ ] Accessiblity
- [ ] Website Optimization
- [ ] Console Foundations
- [ ] Git Basics
- [ ] Front End Performance Optimization

**_Finished June 15, 2017_**
